// Generates docs/explain.md with REAL `EXPLAIN (ANALYZE, BUFFERS)` plans for the
// queries the API actually runs, proving they use the indexes (Index Scan) and
// contrasting keyset with the OFFSET anti-pattern.
//
// Run:  npm run explain   (from backend/)
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { pool, closePool } from '../src/db.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', '..', 'docs', 'explain.md');

const PAGE = 20;

async function explain(sql, params = []) {
  const { rows } = await pool.query(`EXPLAIN (ANALYZE, BUFFERS) ${sql}`, params);
  return rows.map((r) => r['QUERY PLAN']).join('\n');
}

async function main() {
  // Total rows + a mid-feed boundary so the cursor queries are realistic.
  const { rows: countRows } = await pool.query('SELECT count(*)::bigint AS n FROM products');
  const total = Number(countRows[0].n);
  const depth = Math.min(100000, Math.max(0, Math.floor(total / 2)));

  const { rows: bRows } = await pool.query(
    'SELECT created_at, id FROM products ORDER BY created_at DESC, id DESC OFFSET $1 LIMIT 1',
    [depth]
  );
  const boundary = bRows[0];

  const { rows: cRows } = await pool.query('SELECT category FROM products LIMIT 1');
  const category = cRows[0]?.category ?? 'Electronics';

  const sections = [];

  sections.push({
    title: '1. First page (forward, top of feed)',
    why: 'Newest-first page with no cursor. Expect an Index Scan over idx_products_pagination, no Sort node, no Seq Scan.',
    sql: `SELECT id, name, category, price, created_at, updated_at
FROM products
ORDER BY created_at DESC, id DESC
LIMIT ${PAGE}`,
    plan: await explain(
      `SELECT id, name, category, price, created_at, updated_at FROM products ORDER BY created_at DESC, id DESC LIMIT ${PAGE}`
    ),
  });

  sections.push({
    title: '2. Forward page (keyset cursor)',
    why: 'WHERE (created_at, id) < boundary. The row-value comparison becomes an index seek; cost is independent of depth.',
    sql: `SELECT id, name, category, price, created_at, updated_at
FROM products
WHERE (created_at, id) < ($1::timestamptz, $2::bigint)
ORDER BY created_at DESC, id DESC
LIMIT ${PAGE}`,
    plan: await explain(
      `SELECT id, name, category, price, created_at, updated_at FROM products WHERE (created_at, id) < ($1::timestamptz, $2::bigint) ORDER BY created_at DESC, id DESC LIMIT ${PAGE}`,
      [boundary.created_at, boundary.id]
    ),
  });

  sections.push({
    title: '3. Backward page (keyset cursor, reverse scan)',
    why: 'WHERE (created_at, id) > boundary, ORDER BY ASC. Same index, scanned backwards — note "Index Scan Backward" / no separate Sort.',
    sql: `SELECT id, name, category, price, created_at, updated_at
FROM products
WHERE (created_at, id) > ($1::timestamptz, $2::bigint)
ORDER BY created_at ASC, id ASC
LIMIT ${PAGE}`,
    plan: await explain(
      `SELECT id, name, category, price, created_at, updated_at FROM products WHERE (created_at, id) > ($1::timestamptz, $2::bigint) ORDER BY created_at ASC, id ASC LIMIT ${PAGE}`,
      [boundary.created_at, boundary.id]
    ),
  });

  sections.push({
    title: '4. Category-filtered page',
    why: 'WHERE category = $1. Uses idx_products_category_pagination (category leading), seeking to the category slice then walking it ordered.',
    sql: `SELECT id, name, category, price, created_at, updated_at
FROM products
WHERE category = '${category}'
ORDER BY created_at DESC, id DESC
LIMIT ${PAGE}`,
    plan: await explain(
      `SELECT id, name, category, price, created_at, updated_at FROM products WHERE category = $1 ORDER BY created_at DESC, id DESC LIMIT ${PAGE}`,
      [category]
    ),
  });

  sections.push({
    title: `5. OFFSET anti-pattern (depth ${depth.toLocaleString()})`,
    why: `The query we DON'T use. Postgres must produce and discard ${depth.toLocaleString()} rows before returning ${PAGE}. Note the high "actual rows" / time vs. the keyset queries above.`,
    sql: `SELECT id, name, category, price, created_at, updated_at
FROM products
ORDER BY created_at DESC, id DESC
OFFSET ${depth} LIMIT ${PAGE}`,
    plan: await explain(
      `SELECT id, name, category, price, created_at, updated_at FROM products ORDER BY created_at DESC, id DESC OFFSET $1 LIMIT ${PAGE}`,
      [depth]
    ),
  });

  const md = render(total, depth, sections);
  await writeFile(OUT, md, 'utf8');
  console.log(`✔ Wrote ${OUT}`);
}

function render(total, depth, sections) {
  const header = `# EXPLAIN ANALYZE evidence

Auto-generated by \`npm run explain\` (backend/scripts/explain.js) against the live
database. Total rows at generation time: **${total.toLocaleString()}**. Cursor
boundary taken at depth **${depth.toLocaleString()}**.

These are real \`EXPLAIN (ANALYZE, BUFFERS)\` outputs for the exact queries the API
runs. The point: the keyset queries (1–4) use **Index Scan** and finish in well
under a millisecond regardless of depth, while the OFFSET query (5) scans and
discards everything before the page — proving why we avoid it.

> Regenerate any time with \`npm run explain\`. Generated ${new Date().toISOString()}.
`;

  const body = sections
    .map(
      (s) => `
## ${s.title}

${s.why}

\`\`\`sql
${s.sql};
\`\`\`

\`\`\`text
${s.plan}
\`\`\`
`
    )
    .join('\n');

  return header + '\n' + body;
}

main()
  .catch((err) => {
    console.error('explain failed:', err);
    process.exitCode = 1;
  })
  .finally(closePool);
