-- ============================================================================
-- Product catalog schema
-- Designed for O(log n) keyset (cursor) pagination, newest-first.
-- ============================================================================

CREATE TABLE IF NOT EXISTS products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    category    TEXT NOT NULL,
    price       NUMERIC(10, 2) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Composite B-Tree index matching the global feed's ORDER BY (created_at DESC, id DESC).
-- A row-value comparison `(created_at, id) < ($1, $2)` becomes a single index seek.
CREATE INDEX IF NOT EXISTS idx_products_pagination
    ON products (created_at DESC, id DESC);

-- Same idea, but with category as the leading column so a filtered feed
-- (WHERE category = $1) still gets an index seek + ordered scan.
CREATE INDEX IF NOT EXISTS idx_products_category_pagination
    ON products (category, created_at DESC, id DESC);

-- Keep updated_at honest on every UPDATE.
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

DROP TRIGGER IF EXISTS update_products_modtime ON products;
CREATE TRIGGER update_products_modtime
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();
